CREATE DATABASE movies

CREATE TABLE film (
        filmId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        year int NOT NULL
    );


CREATE TABLE genre (
        genreId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        genre_type VARCHAR(50) NOT NULL
    );

CREATE TABLE film_genre (
        filmId int references film(filmId),
        genreId int references genre(genreId),
        constraint film_genre_pkey primary key (filmId, genreId)
    );